# Generated by Django 4.1.7 on 2023-09-05 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('lokasi', models.TextField(max_length=300)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_berakhir', models.DateField()),
                ('status', models.CharField(choices=[('Berlangsung', 'Berlangsung'), ('Selesai', 'Selesai')], default='Berlangsung', max_length=11)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=250)),
                ('keterangan', models.CharField(max_length=250)),
                ('ukuran', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('All Size', 'All Size')], default='All Size', max_length=8)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('item_last_status', models.CharField(choices=[('Terjual', 'Terjual'), ('Tersedia', 'Tersedia'), ('Tidak ada', 'Tidak ada')], default='Tersedia', max_length=18)),
                ('items_event_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.event')),
            ],
        ),
    ]
