# Generated by Django 4.1.7 on 2023-05-08 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('lokasi', models.CharField(max_length=250)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_berakhir', models.DateField()),
                ('status', models.CharField(choices=[('Berlangsung', 'Berlangsung'), ('Selesai', 'Selesai')], default='Berlangsung', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=250)),
                ('keterangan', models.CharField(max_length=250)),
                ('ukuran', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('All Size', 'All Size')], default='All Size', max_length=8)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_last_status', models.CharField(choices=[('Terjual', 'Terjual'), ('Barang tersedia', 'Barang tersedia'), ('Barang tidak ada', 'Barang tidak ada'), ('Barang dalam event', 'Barang dalam event')], default='Barang tersedia', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='EventItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_in_event', models.CharField(choices=[('Terjual', 'Terjual'), ('Barang tersedia', 'Barang tersedia'), ('Barang tidak ada', 'Barang tidak ada'), ('Barang dalam event', 'Barang dalam event')], default='Barang tersedia', max_length=18)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.event')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.inventory')),
            ],
            options={
                'unique_together': {('events', 'items')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='items',
            field=models.ManyToManyField(through='inventory_app.EventItems', to='inventory_app.inventory'),
        ),
    ]
